In [ ]:
#all algos on numerical network and deep learning are written in numpy
# neural network deep learning and coursera
#deep learning.ai

# STALKING 

In [2]:
import numpy as np
a=np.random.randint(1,20,size=20)  #start , step , size
b=np.random.randint(1,10,size=10) 
print(a,b,sep='\n\n')

[ 4 10 18 19  1 10 11 14  2 13 11  9  7  8 17  8  3 19 17  7]

[3 7 3 4 8 5 5 3 5 7]


In [4]:
[True if x in a else False for x in b]

[True, True, True, True, True, False, False, True, False, True]

In [8]:
np.in1d(b,a)        #same numpy function

array([ True,  True,  True,  True,  True,  True, False,  True, False,
       False])

In [ ]:
#merging of two arrays is stalking , concatennation

In [9]:
a=np.arange(1,11)
b=a*3
print(a,b,sep=',''\n')

[ 1  2  3  4  5  6  7  8  9 10],
[ 3  6  9 12 15 18 21 24 27 30]


In [13]:
np.stack((a,b),axis=0) #by default axis o ,  top to bottom

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30]])

In [14]:
np.stack((a,b),axis=1) #by default axis , left to right 

array([[ 1,  3],
       [ 2,  6],
       [ 3,  9],
       [ 4, 12],
       [ 5, 15],
       [ 6, 18],
       [ 7, 21],
       [ 8, 24],
       [ 9, 27],
       [10, 30]])

In [11]:
np.hstack((a,b))       #axis is not equired to be told

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  3,  6,  9, 12, 15, 18, 21,
       24, 27, 30])

In [12]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30]])

In [14]:
a=np.arange(2*2*2).reshape((2,2,2))
b=a+10
print(a,b,sep='/n/n')

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]/n/n[[[10 11]
  [12 13]]

 [[14 15]
  [16 17]]]


In [15]:
np.dstack((a,b))            #dstack??

array([[[ 0,  1, 10, 11],
        [ 2,  3, 12, 13]],

       [[ 4,  5, 14, 15],
        [ 6,  7, 16, 17]]])

In [23]:
a=np.arange(2*2).reshape(2,2)
print(a)
a+5

[[0 1]
 [2 3]]


array([[5, 6],
       [7, 8]])

In [24]:
b=np.full_like(a,5)
print(a,b)

[[0 1]
 [2 3]] [[5 5]
 [5 5]]


In [25]:
a+b

array([[5, 6],
       [7, 8]])

In [26]:
np.column_stack((a,b))

array([[0, 1, 5, 5],
       [2, 3, 5, 5]])

In [27]:
np.row_stack((a,b))

array([[0, 1],
       [2, 3],
       [5, 5],
       [5, 5]])

In [33]:
a=np.arange(6*5).reshape((6,5))

In [34]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [35]:
np.split(a,3)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]])]

In [37]:
np.split(a,2)        #6 rows cant be divided else then 2,3,6

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]])]

In [38]:
a=np.arange(6*6).reshape((6,6))

In [39]:
np.split(a,2,axis=1)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20],
        [24, 25, 26],
        [30, 31, 32]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23],
        [27, 28, 29],
        [33, 34, 35]])]

In [16]:
import numpy as np
a=np.random.randint(1,20,size=20)  #start , step , size
b=np.random.randint(1,10,size=10) 
print(a,b,sep='\n\n')
np.intersect1d(a,b)

[ 5  8 14 17  5  1 16 16 18 17 12 16  1  4 19  4 13  8  5 13]

[3 9 5 9 4 4 9 8 5 3]


array([4, 5, 8])

In [17]:
a = np.random.randint(1,10,size=10)
a

array([4, 8, 4, 9, 7, 9, 3, 8, 7, 1])

In [18]:
np.unique(a)

array([1, 3, 4, 7, 8, 9])

In [20]:
b= np.random.randint(1,10,size=10)
b

array([1, 2, 3, 1, 1, 9, 5, 7, 2, 9])

In [21]:
np.union1d(a,b)

array([1, 2, 3, 4, 5, 7, 8, 9])

In [22]:
np.setdiff1d(a,b)        #those values of a that are not in b are computed

array([4, 8])

In [26]:
np.setxor1d(a,b)       

#works only on differential input
#it will return unique data sets of both the arrays

array([2, 4, 5, 8])

In [24]:
np.setxor1d(a,b)

array([2, 4, 5, 8])

In [25]:
#salayni pandas