# LINEAR ALGEBRA

In [ ]:
......universal functions
......stack
......in1D, 

# BINARY SLICING

In [1]:
import numpy as np

In [ ]:
#in list while slicing value cant be ammended, in array it can be altered

In [3]:
l=[1,2,3,8,0]
l[:2]=3

TypeError: can only assign an iterable

In [4]:
l=np.array([4,8,9,5,6])
l[:2]=5
l

array([5, 5, 9, 5, 6])

In [7]:
lop = np.array([2,4,6,8,10])
lop[2:]=5
lop

array([2, 4, 5, 5, 5])

In [10]:
lop [[1,2,3]]

array([4, 5, 5])

In [14]:
a=np.arange(3*4).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
print(a[0:2])

[[0 1 2 3]
 [4 5 6 7]]


In [16]:
a[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [17]:
a[-3:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [18]:
a[-3:-1]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [21]:
names=np.array(['bob','will','ghj','bob','will','uhib','tfytvgh'])
names

array(['bob', 'will', 'ghj', 'bob', 'will', 'uhib', 'tfytvgh'],
      dtype='<U7')

In [26]:
data=np.random.randn(7,4)
data

array([[-0.3786867 , -0.46950541,  1.15358111, -1.52480471],
       [ 0.11751219, -0.74130198,  0.54833388, -0.54258141],
       [-2.46929522, -1.62616919,  1.15776433,  1.1093665 ],
       [-0.859341  ,  0.30432896,  0.01242196, -1.22453443],
       [ 0.89214214, -0.59746141, -0.35028613,  1.39293177],
       [ 0.47857336,  0.07826176,  1.26227825, -1.12311605],
       [-0.3137397 ,  0.64847933, -0.9121809 ,  0.10854429]])

In [27]:
names=='bob'

array([ True, False, False,  True, False, False, False])

In [28]:
data[[ True, False, False,  True, False, False, False]]

array([[-0.3786867 , -0.46950541,  1.15358111, -1.52480471],
       [-0.859341  ,  0.30432896,  0.01242196, -1.22453443]])

In [29]:
data[names=='bob']

array([[-0.3786867 , -0.46950541,  1.15358111, -1.52480471],
       [-0.859341  ,  0.30432896,  0.01242196, -1.22453443]])

In [31]:
data[:,[0,-1]]                 #it means from all rows bring first and last column

array([[-0.3786867 , -1.52480471],
       [ 0.11751219, -0.54258141],
       [-2.46929522,  1.1093665 ],
       [-0.859341  , -1.22453443],
       [ 0.89214214,  1.39293177],
       [ 0.47857336, -1.12311605],
       [-0.3137397 ,  0.10854429]])

In [30]:
data[(names=="bob")| (names=="will")][:,[0,-1]]      

#when multiple conditions then ()
#: means bring all data, here bring all rows 

array([[-0.3786867 , -1.52480471],
       [ 0.11751219, -0.54258141],
       [-0.859341  , -1.22453443],
       [ 0.89214214,  1.39293177]])

In [34]:
data[~(names=='bob')]

array([[0.11751219, 0.        , 0.54833388, 0.        ],
       [0.        , 0.        , 1.15776433, 1.1093665 ],
       [0.89214214, 0.        , 0.        , 1.39293177],
       [0.47857336, 0.07826176, 1.26227825, 0.        ],
       [0.        , 0.64847933, 0.        , 0.10854429]])

In [35]:
data<0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [36]:
data[data<0]=0

In [37]:
data

array([[0.        , 0.        , 1.15358111, 0.        ],
       [0.11751219, 0.        , 0.54833388, 0.        ],
       [0.        , 0.        , 1.15776433, 1.1093665 ],
       [0.        , 0.30432896, 0.01242196, 0.        ],
       [0.89214214, 0.        , 0.        , 1.39293177],
       [0.47857336, 0.07826176, 1.26227825, 0.        ],
       [0.        , 0.64847933, 0.        , 0.10854429]])

# FANCY INDEXING

In [ ]:
#position can be manipulated
#last at first and first at last

In [40]:
data = np.random.randn(7,4)

In [42]:
data

array([[ 0.48776165, -0.01437051,  1.80078673,  0.16932706],
       [-1.88626873, -2.60947306,  0.99306516, -0.10009396],
       [ 1.07092392,  1.32664227, -0.7252662 , -0.91043352],
       [-0.46317496,  0.81417185,  0.18502501, -0.4805597 ],
       [ 0.49147595, -1.07697494,  0.16948815,  0.18722289],
       [-0.96479373,  0.27780826, -0.40740574, -0.28318334],
       [ 0.63883645,  1.31038067,  0.67811554,  0.5715029 ]])

In [44]:
data[[0,2,4],:]

array([[ 0.48776165, -0.01437051,  1.80078673,  0.16932706],
       [ 1.07092392,  1.32664227, -0.7252662 , -0.91043352],
       [ 0.49147595, -1.07697494,  0.16948815,  0.18722289]])

In [43]:
data[:,[-2,0,-1]]

array([[ 1.80078673,  0.48776165,  0.16932706],
       [ 0.99306516, -1.88626873, -0.10009396],
       [-0.7252662 ,  1.07092392, -0.91043352],
       [ 0.18502501, -0.46317496, -0.4805597 ],
       [ 0.16948815,  0.49147595,  0.18722289],
       [-0.40740574, -0.96479373, -0.28318334],
       [ 0.67811554,  0.63883645,  0.5715029 ]])

In [47]:
data[:,1:][:,[-1,-2,0]]

array([[ 0.16932706,  1.80078673, -0.01437051],
       [-0.10009396,  0.99306516, -2.60947306],
       [-0.91043352, -0.7252662 ,  1.32664227],
       [-0.4805597 ,  0.18502501,  0.81417185],
       [ 0.18722289,  0.16948815, -1.07697494],
       [-0.28318334, -0.40740574,  0.27780826],
       [ 0.5715029 ,  0.67811554,  1.31038067]])

In [48]:
a=np.zeros((8,4))

In [49]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
for i, v  in enumerate(a):             #for i, _ in enumerate(a):
    a[i]=i
a
    
#enumerate  return value and its index , i is index , v is values

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [50]:
for i in range(len(a)):
    a[i]=i
a

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [53]:
a =np.arange(4*4).reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
a.T                #attribute as no ()

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [56]:
a.transpose()                    #as transpose is a method so () will come

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [59]:
b = np.arange(12).reshape(4,3)
np.dot(a,b)

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262],
       [258, 312, 366]])

In [60]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a,b,sep='\n\n')

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


In [61]:
a*b

array([[ 5, 12],
       [21, 32]])

In [51]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [62]:
print(a@b)        #@: dot product...first row , first column

[[19 22]
 [43 50]]


In [52]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [63]:
arr=np.arange(1,2*2*4+1).reshape(2,2,4)    #to start from 1
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [56]:
arr=np.arange(10,2*2*4+10).reshape(2,2,4)    #to start from 10
arr

array([[[10, 11, 12, 13],
        [14, 15, 16, 17]],

       [[18, 19, 20, 21],
        [22, 23, 24, 25]]])

In [57]:
arr.T

array([[[10, 18],
        [14, 22]],

       [[11, 19],
        [15, 23]],

       [[12, 20],
        [16, 24]],

       [[13, 21],
        [17, 25]]])

In [64]:
arr
arr.transpose((1,0,2))      #transpose in 3d ...t in numpy in animations

array([[[10, 11, 12, 13],
        [18, 19, 20, 21]],

       [[14, 15, 16, 17],
        [22, 23, 24, 25]]])

In [63]:
arr.shape

(2, 2, 4)

In [59]:
arr.T

array([[[10, 18],
        [14, 22]],

       [[11, 19],
        [15, 23]],

       [[12, 20],
        [16, 24]],

       [[13, 21],
        [17, 25]]])

In [61]:
arr.transpose??

In [64]:
arr=np.arange(1,2*2*4+1).reshape(2,2,4)    #to start from 1
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [65]:
arr.swapaxes(1,2) #index positions are altered,dimensions r changed

array([[[ 1,  5],
        [ 2,  6],
        [ 3,  7],
        [ 4,  8]],

       [[ 9, 13],
        [10, 14],
        [11, 15],
        [12, 16]]])

In [66]:
arr.swapaxes??

In [68]:
a=np.arange(3*4).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
a.swapaxes(1,0)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

# UNIVERAL FUNCTIONS

In [70]:
a=np.array([1,2,-3,-4,-4,-7])
np.abs(a)       #mean absoltue error in ai

array([1, 2, 3, 4, 4, 7])

In [71]:
np.fabs(a)

array([1., 2., 3., 4., 4., 7.])

In [73]:
np.exponent??

Object `np.exponent` not found.


In [ ]:
#ceil...for round off =2.3,2.7
=3

#floor=2.3,2.7
=2

In [74]:
a=np.array([1,8,9,6,4,5,6])
f,w=np.modf(a)                         #it devides whole and float no
print(w,f,sep='\n')

[1. 8. 9. 6. 4. 5. 6.]
[0. 0. 0. 0. 0. 0. 0.]


In [77]:
a = np.array([1.2,2.8,3.6,4.1,5.2,6.9])
f,w = np.modf(a)
w                                       #we can say that modf separates decimal and whole no part 

array([1., 2., 3., 4., 5., 6.])

In [78]:
f

array([0.2, 0.8, 0.6, 0.1, 0.2, 0.9])

In [83]:
a==np.array([11,20,25])
np.fmod(a,3)

array([2, 2, 1], dtype=int32)

In [84]:
a=np.array([1,2,3])
b=np.array([-1,5,7])
np.maximum(a,b)

array([1, 5, 7])

In [85]:
np.minimum(a,b)

array([-1,  2,  3])

In [86]:
np.fmax(a,b)

array([1, 5, 7])

In [92]:
np.fmin(a,b)

array([-1,  2,  3])

# meshgrid

In [98]:
a=np.arange(3*2).reshape((3,2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [88]:
a

array([1, 2, 3])

In [87]:
np.meshgrid(a)                   

#makes rows and column same by index

[array([1, 2, 3])]

In [ ]:
MATPLOTLIB ...salyni git

# WHERE

In [101]:
a=np.arange(36)
if a%3==0

array([ True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False])

In [103]:
#np.where(CONDITION,TRUE,FALSE)

In [104]:
np.where(a%3,'yes','no')

array(['no', 'yes', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'yes', 'no',
       'yes', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'yes', 'no', 'yes',
       'yes', 'no', 'yes', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'yes',
       'no', 'yes', 'yes', 'no', 'yes', 'yes'], dtype='<U3')

# MATHEMATICAL AND STATISTICAL METODS

In [89]:
a=np.arange(3*4).reshape((3,4))

In [90]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
a.mean()

5.5

In [92]:
a.sum()

66

In [93]:
np.sum(a)

66

In [94]:
np.sum(a,axis=0)              #top to bottom:0
                              #left to right:1

array([12, 15, 18, 21])

In [95]:
#it takes sum of each column

In [96]:
np.sum(a,axis=1) 

array([ 6, 22, 38])

In [97]:
# mean , media, mode : central tendency

In [98]:
a.mean(axis=0)       #sum of elements in each row/no of elemnets in that row

array([4., 5., 6., 7.])

In [99]:
a.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66], dtype=int32)

In [100]:
a.cumprod(axis=1)

array([[   0,    0,    0,    0],
       [   4,   20,  120,  840],
       [   8,   72,  720, 7920]], dtype=int32)

In [ ]:
argmin ....sbse chote value ka index return kry ga
armax......sbse bare vaulue ka index return kry ga
np.argsort.....gives the indices that will sort the array

In [102]:
a=np.array([1,2,34,6,7,9])
np.argmax(a)

2

In [119]:
np.argsort(a)

array([0, 1, 3, 4, 5, 2], dtype=int64)

In [107]:
a[[0, 1, 3, 4, 5, 2]]

array([ 1,  2,  6,  7,  9, 34])

In [ ]:
split and stack
uit topic