In [ ]:
rank and dimension same
shape tells  how many no of elements in each dimension

# multidimensional array object

In [1]:
import numpy as np
l=np.arange(1,13).reshape((12,1))
l

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [2]:
l.itemsize

4

# INDEXING

# RANDOM 

In [ ]:
shape attribute
reshape function

In [5]:
a=np.arange(1,28).reshape((3,3,3))          #reshape always take tuple

In [6]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [7]:
a.shape

(3, 3, 3)

In [8]:
a.ndim

3

In [7]:
a.shape=(3,9)             #shape is in memory operation(real data ko ja k change krta aa)

In [12]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [13]:
np.zeros((3,3,3))           #we have to tell the dimension

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [14]:
np.zeros_like(a) 

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [15]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [16]:
np.ones_like(a)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [17]:
np.empty                  #it collects garbage value , randomly form memory


<function numpy.empty>

In [18]:
np.empty((2,2))

array([[2.50398569e+262, 7.32802202e+223],
       [4.51826701e-307, 1.35245338e+161]])

In [19]:
np.empty_like(a,dtype=np.float64)

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [19]:
np.full((2,2,3),fill_value=5)

array([[[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]]])

In [21]:
np.empty_like(a,dtype=np.int32)

array([[[         0,          0,          0],
        [         0,          0,          0],
        [         0,          0,          0]],

       [[         0,          0,          0],
        [         0,          0,          0],
        [         0,          0,          0]],

       [[         0,          0,          0],
        [         0,          0,          0],
        [         0,          0, -184511432]]])

In [23]:
b= np.full((2,2,4),fill_value=4)
b

array([[[4, 4, 4, 4],
        [4, 4, 4, 4]],

       [[4, 4, 4, 4],
        [4, 4, 4, 4]]])

In [24]:
np.full_like(b,8)

array([[[8, 8, 8, 8],
        [8, 8, 8, 8]],

       [[8, 8, 8, 8],
        [8, 8, 8, 8]]])

In [25]:
np.full_like(a,7)              #like in line function

array([[[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]]])

In [26]:
np.ones((2,3)) * 5

array([[5., 5., 5.],
       [5., 5., 5.]])

In [27]:
np.zeros((2,3)) *3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
eye,identity

In [30]:
np.eye(6)        #eygon vector , at diagonal identity

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [28]:
np.eye??

In [29]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.identity??

# DATA TYPE FOR ND ARRAY

In [32]:
a=np.arange(1,13).reshape((3,4)) #reshape mein dtype convert ni hote shape mein hote
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
a.dtype

dtype('int32')

In [37]:
a=np.arange(1,13).astype(np.float64).reshape((3,4))
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [38]:
a.dtype

dtype('float64')

In [ ]:
#(reshape(astype(range(1,12))))

In [ ]:
astype function is used to change existing datatype(attribute) of function
kaam same

In [33]:
a=np.arange(1,13,dtype="float").reshape((3,4))
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [41]:
c = np.arange(5).astype(np.float64).reshape(1,5)
c

array([[0., 1., 2., 3., 4.]])

In [43]:
a = np.arange(1,13).astype(np.character).reshape(4,3)
a

array([[b'1', b'2', b'3'],
       [b'4', b'5', b'6'],
       [b'7', b'8', b'9'],
       [b'10', b'11', b'12']], dtype='|S11')

In [44]:
a=np.arange(1,13).astype(np.character).reshape(3,4)
a

array([[b'1', b'2', b'3', b'4'],
       [b'5', b'6', b'7', b'8'],
       [b'9', b'10', b'11', b'12']], dtype='|S11')

In [45]:
a=np.array([1,2,4],dtype=np.float32)

In [46]:
a

array([1., 2., 4.], dtype=float32)

In [47]:
a1=np.array([1,2,4],dtype=np.int32)

In [48]:
a1.dtype

dtype('int32')

In [49]:
print(type(a))

<class 'numpy.ndarray'>


In [50]:
a=np.array([1,2,4],dtype='int')
print(a.dtype)

int32


In [51]:
a=np.array([1,2,4],dtype=np.int64)

In [52]:
a.dtype

dtype('int64')

In [53]:
a=np.array([1,2,4],dtype='i1')

In [54]:
a

array([1, 2, 4], dtype=int8)

In [51]:
def abc(x):
    try:
        x=str(x)
        return np.int64("".join([i for i in x if str.isnumeric(i)]))
    except:
        return 0
    
abc("jh435gaeffjqwfbjkw84444")

43584444

In [60]:
def abc(x):
    try:
        x= str(x)
        return np.int64("".join([i for i in x if str.isnumeric(i)]))
    except:
        return 1


abc("ij2rne2j4342iu5")

2243425

In [54]:
a=np.arange(1,12,dtype=np.float64)
b=np.arange(1,4)
a.dtype
b.dtype

dtype('int32')

In [ ]:
b.astype()

In [62]:
a=np.arange(1,28).reshape((3,3,3))

In [63]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [64]:
a %5 == 0

array([[[False, False, False],
        [False,  True, False],
        [False, False, False]],

       [[ True, False, False],
        [False, False,  True],
        [False, False, False]],

       [[False,  True, False],
        [False, False, False],
        [ True, False, False]]])

In [65]:
a[a%5==0]

array([ 5, 10, 15, 20, 25])

In [66]:
a[(a%5==0) & (a%3==0)]

array([15])

In [67]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [68]:
a[1][1][1]        
#14 required

14

In [69]:
a[1:]

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [70]:
a[1:,1:,1:]

array([[[14, 15],
        [17, 18]],

       [[23, 24],
        [26, 27]]])

In [66]:
a[1,1,1]

14

In [71]:
a[1:][1:][1:]

array([], shape=(0, 3, 3), dtype=int32)